"""
Full-Year MILP — 7 Thesis Figures (spec §8.1)

Reads from milp_outputs/design_results_master.csv and
milp_outputs/replay_summary_master.csv (generated by run_all.py Stage 3).
Saves figures to docs/figures/.
"""
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT  = ROOT / 'milp_outputs'
FIG  = ROOT / 'docs' / 'figures'
FIG.mkdir(parents=True, exist_ok=True)

CASE_ORDER = ['C0', 'C1', 'C2', 'C3', 'C_PFI']
LABELS = [
    'C0\nDet PV\nDet Load',
    'C1\nProb PV\nDet Load',
    'C2\nDet PV\nPert Load',
    'C3\nProb PV\nPert Load',
    'C_PFI\nPerfect\nForecast',
]
COLORS = ['#4ECDC4', '#FF6B6B', '#45B7D1', '#FFA07A', '#98D8C8']


def load_data():
    design = pd.read_csv(OUT / 'design_results_master.csv')
    replay = pd.read_csv(OUT / 'replay_summary_master.csv')

    # Reindex both to CASE_ORDER for consistent ordering
    design = design.set_index('case_id').reindex(CASE_ORDER).reset_index()
    replay = replay.set_index('case_id').reindex(CASE_ORDER).reset_index()

    # Compute gap_pct: (replay_total - J_A) / J_A * 100
    design['gap_pct'] = (design['replay_total_M'] - design['J_A_M']) / design['J_A_M'] * 100

    # Load per-case monthly bills
    monthly = {}
    for case_id in CASE_ORDER:
        mb = pd.read_csv(OUT / f'replay_monthly_bill_{case_id}.csv')
        monthly[case_id] = mb  # cols: month_id, total_NTD, ...

    # Compute worst_bill_M per case
    replay['worst_bill_M'] = [
        monthly[cid]['total_NTD'].max() / 1e6 for cid in CASE_ORDER
    ]

    return design, replay, monthly


def main():
    design, replay, monthly = load_data()
    cases = CASE_ORDER

    # ── Fig 1: Sizing comparison (CC, P_B, E_B) ─────────────
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    axes[0].bar(LABELS, design['CC_kW'], color=COLORS)
    axes[0].set_ylabel('Contract Capacity (kW)')
    axes[0].set_title('Contract Capacity')
    for i, v in enumerate(design['CC_kW']):
        axes[0].text(i, v + 20, f'{v:.0f}', ha='center', fontsize=9)

    axes[1].bar(LABELS, design['P_B_kW'], color=COLORS)
    axes[1].set_ylabel('BESS Power (kW)')
    axes[1].set_title('BESS Power')
    for i, v in enumerate(design['P_B_kW']):
        axes[1].text(i, v + 10, f'{v:.0f}', ha='center', fontsize=9)

    axes[2].bar(LABELS, design['E_B_kWh'], color=COLORS)
    axes[2].set_ylabel('BESS Energy (kWh)')
    axes[2].set_title('BESS Energy')
    for i, v in enumerate(design['E_B_kWh']):
        axes[2].text(i, v + 50, f'{v:.0f}', ha='center', fontsize=9)

    fig.suptitle('Figure 1: Sizing Comparison (CC*, P_B*, E_B*)', fontsize=14, fontweight='bold')
    fig.tight_layout()
    fig.savefig(FIG / 'fig1_sizing_comparison.png', dpi=150, bbox_inches='tight')
    plt.close()

    # ── Fig 2: Replay annual cost comparison ─────────────────
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.bar(LABELS, replay['replay_total_M'], color=COLORS, edgecolor='black', linewidth=0.5)
    ax.set_ylabel('Annual Cost (M NTD)')
    ax.set_title('Figure 2: Replay Annual Total Cost', fontsize=14, fontweight='bold')
    for i, v in enumerate(replay['replay_total_M']):
        ax.text(i, v + 0.1, f'{v:.2f}M', ha='center', fontsize=10)
    ax.set_ylim(bottom=94)
    fig.tight_layout()
    fig.savefig(FIG / 'fig2_replay_cost.png', dpi=150, bbox_inches='tight')
    plt.close()

    # ── Fig 3: Over-contract fee and worst-month bill ────────
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    axes[0].bar(LABELS, replay['overcontract_M'], color=COLORS)
    axes[0].set_ylabel('Over-Contract Fee (M NTD)')
    axes[0].set_title('Annual Over-Contract Fee')
    for i, v in enumerate(replay['overcontract_M']):
        axes[0].text(i, v + 0.05, f'{v:.2f}M', ha='center', fontsize=9)

    axes[1].bar(LABELS, replay['worst_bill_M'], color=COLORS)
    axes[1].set_ylabel('Worst Month Bill (M NTD)')
    axes[1].set_title('Worst-Month Bill')
    for i, v in enumerate(replay['worst_bill_M']):
        axes[1].text(i, v + 0.02, f'{v:.2f}M', ha='center', fontsize=9)

    fig.suptitle('Figure 3: Over-Contract & Worst-Month Bill (Replay)', fontsize=14, fontweight='bold')
    fig.tight_layout()
    fig.savefig(FIG / 'fig3_overcontract_worst.png', dpi=150, bbox_inches='tight')
    plt.close()

    # ── Fig 4: RE20 achievement and T-REC gap ────────────────
    fig, ax = plt.subplots(figsize=(9, 5))
    re_vals   = replay['RE_pct'].values
    trec_gwh  = design['trec_shortfall_kwh'].values / 1e6  # GWh shortfall
    ax.bar(LABELS, re_vals, color=COLORS)
    ax.axhline(y=20, color='red', linestyle='--', linewidth=1.5, label='RE20 Target (20%)')
    ax.set_ylabel('RE Achievement (%)')
    ax.set_title('Figure 4: RE20 Achievement & T-REC Gap', fontsize=14, fontweight='bold')
    for i in range(len(cases)):
        ax.text(i, re_vals[i] + 0.3,
                f'{re_vals[i]:.1f}%\nShortfall: {trec_gwh[i]:.2f} GWh',
                ha='center', fontsize=8)
    ax.set_ylim(0, 25)
    ax.legend()
    fig.tight_layout()
    fig.savefig(FIG / 'fig4_re20_trec.png', dpi=150, bbox_inches='tight')
    plt.close()

    # ── Fig 5: Dispatch trace (sample week, truth data) ──────
    truth_path = ROOT / 'bridge_outputs_fullyear' / 'full_year_replay_truth_package.parquet'
    truth = pd.read_parquet(truth_path)
    # Pick the first 7 days of July
    july_days = sorted(truth[truth['month_id'] == 7]['day_index'].unique())[:7]

    fig, axes = plt.subplots(2, 1, figsize=(16, 10), sharex=True)
    subset = truth[truth['day_index'].isin(july_days)].sort_values(['day_index', 'hour_local'])
    hours = np.arange(len(subset))

    for ax_idx, (case_label, pv_label) in enumerate([('C0', 'Det PV'), ('C1', 'Prob PV')]):
        ax = axes[ax_idx]
        ax.fill_between(hours, 0, subset['load_realized_kw'].values,
                        alpha=0.3, color='gray', label='Load (realized)')
        ax.fill_between(hours, 0, subset['pv_realized_kw'].values,
                        alpha=0.6, color='gold', label='PV (realized)')
        ax.set_ylabel('Power (kW)')
        ax.set_title(f'{case_label}: {pv_label} — July Week Dispatch (Truth)')
        ax.legend(loc='upper right')
        ax.set_xlim(0, len(hours))

    axes[1].set_xlabel('Hour Index')
    fig.suptitle('Figure 5: Chronological Dispatch Trace (Truth)', fontsize=14, fontweight='bold')
    fig.tight_layout()
    fig.savefig(FIG / 'fig5_dispatch_trace.png', dpi=150, bbox_inches='tight')
    plt.close()

    # ── Fig 6: Monthly bill breakdown (stacked bar) ──────────
    fig, ax = plt.subplots(figsize=(14, 6))
    width = 0.16
    months = list(range(1, 13))
    month_labels = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

    for ci, case_id in enumerate(cases):
        mb = monthly[case_id]
        vals = []
        for m in months:
            row = mb[mb['month_id'] == m]
            vals.append(float(row['total_NTD'].iloc[0]) / 1e6 if len(row) else 0.0)
        x = np.arange(len(months)) + ci * width
        ax.bar(x, vals, width, label=LABELS[ci].replace('\n', ' '), color=COLORS[ci])

    ax.set_xticks(np.arange(len(months)) + 2 * width)
    ax.set_xticklabels(month_labels)
    ax.set_ylabel('Monthly Bill (M NTD)')
    ax.set_title('Figure 6: Monthly Bill Breakdown (Replay)', fontsize=14, fontweight='bold')
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(FIG / 'fig6_monthly_bills.png', dpi=150, bbox_inches='tight')
    plt.close()

    # ── Fig 7: Design-to-replay gap comparison ───────────────
    gaps = design['gap_pct'].values
    fig, ax = plt.subplots(figsize=(9, 5))
    bar_colors = [COLORS[i] for i in range(len(cases))]
    ax.bar(LABELS, gaps, color=bar_colors, edgecolor='black', linewidth=0.5)
    ax.axhline(y=0, color='black', linewidth=0.8)
    ax.set_ylabel('Gap (%) = (Replay − Layer A) / Layer A × 100')
    ax.set_title('Figure 7: Design-to-Replay Gap', fontsize=14, fontweight='bold')
    for i, v in enumerate(gaps):
        ax.text(i, v + (0.2 if v >= 0 else -0.5), f'{v:+.1f}%', ha='center', fontsize=10)
    fig.tight_layout()
    fig.savefig(FIG / 'fig7_gap.png', dpi=150, bbox_inches='tight')
    plt.close()

    print(f"All 7 figures saved to {FIG}")
    for f in sorted(FIG.glob('fig*.png')):
        print(f"  {f.name}")


if __name__ == '__main__':
    main()
